-- ============================================
-- TrekTrack Mock Data - 100 rows per table
-- Run after schema.sql
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- MOCK: places (famous attractions in Vietnam)
-- ============================================
INSERT INTO public.places (id, name, description, latitude, longitude, category, image_url, popularity_score, is_featured, created_at) VALUES
(uuid_generate_v4(), 'Fansipan', 'Núi cao nhất Việt Nam, đỉnh núi hùng vĩ 3.143m', 22.3005, 103.7866, 'mountain', 'https://images.unsplash.com/fansipan.jpg', 950, true, NOW()),
(uuid_generate_v4(), 'Mộc Châu', 'Cao nguyên xanh mướt với thung lũng hoa và đồi chè', 20.9101, 104.6329, 'highland', 'https://images.unsplash.com/moc-chau.jpg', 880, true, NOW()),
(uuid_generate_v4(), 'Đà Lạt', 'Thành phố ngàn hoa, khí hậu mát mẻ quanh năm', 11.9404, 108.4581, 'city', 'https://images.unsplash.com/da-lat.jpg', 920, true, NOW()),
(uuid_generate_v4(), 'Tam Đảo', 'Thị trấn nghỉ dưỡng trên núi với khung cảnh tuyệt đẹp', 21.4406, 105.6425, 'mountain', 'https://images.unsplash.com/tam-dao.jpg', 850, true, NOW()),
(uuid_generate_v4(), 'Cát Bà', 'Hòn đảo lớn nhất vịnh Hạ Long với rừng nguyên sinh', 20.7281, 106.9628, 'island', 'https://images.unsplash.com/cat-ba.jpg', 800, true, NOW()),
(uuid_generate_v4(), 'Sapa', 'Vùng đất của những ruộng bậc thang và nét văn hóa dân tộc', 22.3362, 103.8425, 'mountain', 'https://images.unsplash.com/sapa.jpg', 890, true, NOW()),
(uuid_generate_v4(), 'Mù Cang Chải', 'Ruộng bậc thang nổi tiếng mùa lúa chín vàng', 21.1595, 104.3622, 'mountain', 'https://images.unsplash.com/mu-cang-chai.jpg', 870, true, NOW()),
(uuid_generate_v4(), 'Ninh Bình', 'Cố đô Hoa Lư với hang động và danh thắng Tràng An', 20.1091, 105.9076, 'heritage', 'https://images.unsplash.com/ninh-binh.jpg', 780, false, NOW()),
(uuid_generate_v4(), 'Phong Nha', 'Vườn quốc gia với hệ thống hang động kỳ vĩ', 17.5636, 106.2839, 'cave', 'https://images.unsplash.com/phong-nha.jpg', 820, true, NOW()),
(uuid_generate_v4(), 'Bạch Mã', 'Vườn quốc gia với rừng nguyên sinh và thác nước', 16.2055, 107.8542, 'forest', 'https://images.unsplash.com/bach-ma.jpg', 750, false, NOW()),
(uuid_generate_v4(), 'Côn Đảo', 'Quần đảo hoang sơ với bãi biển đẹp và lịch sử', 8.7033, 106.6233, 'island', 'https://images.unsplash.com/con-dao.jpg', 790, true, NOW()),
(uuid_generate_v4(), 'Phú Quốc', 'Đảo ngọc với bãi biển trong xanh và san hô', 10.4801, 103.9200, 'island', 'https://images.unsplash.com/phu-quoc.jpg', 950, true, NOW()),
(uuid_generate_v4(), 'Tràng An', 'Di sản thế giới với hang động và thuyền buồm', 20.2130, 105.9250, 'heritage', 'https://images.unsplash.com/trang-an.jpg', 830, true, NOW()),
(uuid_generate_v4(), 'Mekong Delta', 'Vùng đồng bằng sông Cửu Long với kênh rạch', 10.0452, 105.7469, 'river', 'https://images.unsplash.com/mekong.jpg', 710, false, NOW()),
(uuid_generate_v4(), 'Bảy Giọc', 'Hang động đá vôi trong vịnh Lan Hạ', 20.7294, 107.4297, 'cave', 'https://images.unsplash.com/bay-gioc.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Y Tý', 'Làng cổ nằm trên độ cao 1800m với ruộng bậc thang', 22.6167, 103.8167, 'mountain', 'https://images.unsplash.com/y-ty.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Bảo Lộc', 'Thành phố trà và lụa với khí hậu mát mẻ', 11.5494, 108.1028, 'highland', 'https://images.unsplash.com/bao-loc.jpg', 580, false, NOW()),
(uuid_generate_v4(), 'Lai Châu', 'Vùng đất với cảnh quan núi non hùng vĩ', 22.3833, 103.4500, 'mountain', 'https://images.unsplash.com/lai-chau.jpg', 650, false, NOW()),
(uuid_generate_v4(), 'Tà Xùa', 'Điểm trekking với đồi chè và cảnh quan núi', 21.4167, 104.5833, 'highland', 'https://images.unsplash.com/ta-xua.jpg', 720, true, NOW()),
(uuid_generate_v4(), 'Bình Liêu', 'Thị trấn biên giới với thung lũng Leekoong', 21.5500, 107.6000, 'mountain', 'https://images.unsplash.com/binh-lieu.jpg', 610, false, NOW()),
(uuid_generate_v4(), 'Tây Yên Tử', 'Khu di tích và danh thắng núi Yên Tử', 21.1708, 106.6625, 'mountain', 'https://images.unsplash.com/tay-yen-tu.jpg', 770, true, NOW()),
(uuid_generate_v4(), 'Ba Bể', 'Vườn quốc gia với hồ nước ngọt lớn nhất Việt Nam', 22.4417, 105.6167, 'lake', 'https://images.unsplash.com/ba-be.jpg', 740, true, NOW()),
(uuid_generate_v4(), 'Cao Bằng', 'Vùng đất với thác Bản Giốc và hang Puong', 22.1333, 106.2500, 'waterfall', 'https://images.unsplash.com/cao-bang.jpg', 760, true, NOW()),
(uuid_generate_v4(), 'Hà Giang', 'Cao nguyên đá với đèo Mã Pì Lèng và Mậu Duệ', 23.1167, 105.0000, 'mountain', 'https://images.unsplash.com/ha-giang.jpg', 880, true, NOW()),
(uuid_generate_v4(), 'Sơn La', 'Tỉnh miền núi với đèo Khau Phạ và Nghĩa Lộ', 21.3250, 103.9111, 'mountain', 'https://images.unsplash.com/son-la.jpg', 670, false, NOW()),
(uuid_generate_v4(), 'Lào Cai', 'Cửa ngõ phía Bắc với Sapa và biên giới', 22.4856, 103.9711, 'mountain', 'https://images.unsplash.com/lao-cai.jpg', 850, true, NOW()),
(uuid_generate_v4(), 'Yên Bái', 'Vùng đất với Mù Cang Chải và Trạm Tấu', 21.7167, 104.9167, 'mountain', 'https://images.unsplash.com/yen-bai.jpg', 730, false, NOW()),
(uuid_generate_v4(), 'Điện Biên', 'Nơi diễn ra chiến thắng Điện Biên Phủ', 21.3833, 103.0167, 'heritage', 'https://images.unsplash.com/dien-bien.jpg', 700, false, NOW()),
(uuid_generate_v4(), 'Pù Luông', 'Khu bảo tồn thiên nhiên với rừng và ruộng', 20.4167, 105.3333, 'forest', 'https://images.unsplash.com/pu-luong.jpg', 750, true, NOW()),
(uuid_generate_v4(), 'Quảng Bình', 'Vùng đất với động Phong Nha và bờ biển', 17.6144, 106.3628, 'coast', 'https://images.unsplash.com/quang-binh.jpg', 780, true, NOW()),
(uuid_generate_v4(), 'Huế', 'Cố đô với lăng tẩm và đại nội', 16.4637, 107.5708, 'heritage', 'https://images.unsplash.com/hue.jpg', 870, true, NOW()),
(uuid_generate_v4(), 'Đà Nẵng', 'Thành phố biển với Ngũ Hành Sơn và Bà Nà', 16.0544, 108.2022, 'city', 'https://images.unsplash.com/da-nang.jpg', 890, true, NOW()),
(uuid_generate_v4(), 'Hội An', 'Phố cổ với lịch sử và ẩm thực phong phú', 15.8801, 108.3380, 'heritage', 'https://images.unsplash.com/hoi-an.jpg', 920, true, NOW()),
(uuid_generate_v4(), 'Kon Tum', 'Vùng cao nguyên với nhà sàn và rừng', 14.3497, 108.0006, 'highland', 'https://images.unsplash.com/kon-tum.jpg', 640, false, NOW()),
(uuid_generate_v4(), 'Pleiku', 'Thành phố cao nguyên với hồ TNưng', 13.9833, 108.0000, 'highland', 'https://images.unsplash.com/pleiku.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Đắk Lắk', 'Vùng hồ Lắk với thuyền độc mộc và rừng', 12.8833, 108.0500, 'lake', 'https://images.unsplash.com/dak-lak.jpg', 700, false, NOW()),
(uuid_generate_v4(), 'Đắk Nông', 'Vườn quốc gia Tà Đùng - Tuyết Sơn', 12.0333, 107.7833, 'forest', 'https://images.unsplash.com/dak-nong.jpg', 660, false, NOW()),
(uuid_generate_v4(), 'Tây Ninh', 'Núi Bà Đen với đền thờ và cáp treo', 11.3500, 106.1333, 'mountain', 'https://images.unsplash.com/ba-den.jpg', 730, true, NOW()),
(uuid_generate_v4(), 'Đồng Nai', 'Vườn quốc gia Cát Tiên với rừng nguyên sinh', 11.4167, 107.3667, 'forest', 'https://images.unsplash.com/cat-tien.jpg', 760, true, NOW()),
(uuid_generate_v4(), 'Cần Thơ', 'Chợ nổi Cái Răng và vườn cây ăn trái', 10.0341, 105.7872, 'river', 'https://images.unsplash.com/can-tho.jpg', 820, true, NOW()),
(uuid_generate_v4(), 'Cà Mau', 'Đất mũi Cà Mau với rừng ngập mặn', 8.6333, 104.7833, 'forest', 'https://images.unsplash.com/ca-mau.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Lý Sơn', 'Hòn đảo với ruộng tỏi và núi lửa', 15.3833, 109.1167, 'island', 'https://images.unsplash.com/ly-son.jpg', 760, true, NOW()),
(uuid_generate_v4(), 'Nam Du', 'Quần đảo với hòn lớn và hòn nhỏ', 9.6833, 104.3167, 'island', 'https://images.unsplash.com/nam-du.jpg', 720, true, NOW()),
(uuid_generate_v4(), 'Phú Yên', 'Vịnh Vũng Rô và núi Đá Bia', 13.0833, 109.2833, 'coast', 'https://images.unsplash.com/phu-yen.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Ninh Thuận', 'Vùng đất khô hạn với nho và táo', 11.5667, 109.0000, 'coast', 'https://images.unsplash.com/ninh-thuan.jpg', 560, false, NOW()),
(uuid_generate_v4(), 'Nha Trang', 'Thành phố biển với Hòn Mun', 12.2388, 109.1967, 'coast', 'https://images.unsplash.com/nha-trang.jpg', 920, true, NOW()),
(uuid_generate_v4(), 'Phan Thiết', 'Mũi Né với đồi cát và biển xanh', 10.9333, 108.1000, 'coast', 'https://images.unsplash.com/phan-thiet.jpg', 780, false, NOW()),
(uuid_generate_v4(), 'Lang Biang', 'Núi Lang Biang với rừng thông và thác', 11.9500, 108.4500, 'mountain', 'https://images.unsplash.com/lang-biang.jpg', 800, true, NOW()),
(uuid_generate_v4(), 'Thung Lũng Tình Yêu', 'Thung lũng hoa và hồ Xuân Hương', 11.9467, 108.4383, 'highland', 'https://images.unsplash.com/tlt.jpg', 860, true, NOW()),
(uuid_generate_v4(), 'Hồ Suối Vàng', 'Hồ nước yên tĩnh giữa rừng thông', 11.9833, 108.4500, 'lake', 'https://images.unsplash.com/ho-suoi-vang.jpg', 740, false, NOW()),
(uuid_generate_v4(), 'Bidoup National Park', 'Núi Ngọc Linh với rừng nguyên sinh', 12.1833, 108.7167, 'forest', 'https://images.unsplash.com/bidoup.jpg', 700, false, NOW()),
(uuid_generate_v4(), 'Tà Đùng', 'Hồ Tà Đùng với cảnh quan tuyệt đẹp', 12.0333, 107.7833, 'lake', 'https://images.unsplash.com/ta-dung.jpg', 760, true, NOW()),
(uuid_generate_v4(), 'Ea Soup Waterfall', 'Thác Ea Soup giữa rừng nhiệt đới', 12.7000, 108.0333, 'waterfall', 'https://images.unsplash.com/ea-soup.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Chư Mom Ray', 'Vườn quốc gia với động khỉ', 14.4500, 107.6000, 'forest', 'https://images.unsplash.com/chu-mom-ray.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Ngọc Linh', 'Núi Ngọc Linh với rừng và thác', 15.1500, 107.9833, 'mountain', 'https://images.unsplash.com/ngoc-linh.jpg', 720, false, NOW()),
(uuid_generate_v4(), 'Tú Làn Cave', 'Hang Tú Làn với thung lũng hang động', 17.5167, 106.2833, 'cave', 'https://images.unsplash.com/tu-lan.jpg', 780, true, NOW()),
(uuid_generate_v4(), 'Gio Việt Beach', 'Bãi biển hoang sơ Gio Việt', 16.9167, 107.2000, 'coast', 'https://images.unsplash.com/gio-viet.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Bà Nà Hill', 'Núi Bà Nà với cáp treo và làng Pháp', 15.9833, 108.0333, 'mountain', 'https://images.unsplash.com/ba-na.jpg', 890, true, NOW()),
(uuid_generate_v4(), 'Lũng Ếch Cave', 'Hang động Lũng Ếch với cảnh quan', 15.0833, 108.6333, 'cave', 'https://images.unsplash.com/lung-ech.jpg', 580, false, NOW()),
(uuid_generate_v4(), 'Quy Nhơn', 'Bãi biển và núi Bánh Ít', 13.7833, 109.2167, 'coast', 'https://images.unsplash.com/quy-nhon.jpg', 760, false, NOW()),
(uuid_generate_v4(), 'Gành Đá Đĩa', 'Địa hình đá tự nhiên độc đáo', 13.0333, 109.3333, 'coast', 'https://images.unsplash.com/ganh-da.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Ninh Chữ Beach', 'Bãi biển hoang sơ Ninh Chữ', 11.5833, 109.0833, 'coast', 'https://images.unsplash.com/ninh-chu.jpg', 640, false, NOW()),
(uuid_generate_v4(), 'Mũi Né Dunes', 'Đồi cát Mũi Né và làng chài', 10.9500, 108.0667, 'coast', 'https://images.unsplash.com/mui-ne.jpg', 780, false, NOW()),
(uuid_generate_v4(), 'Bạch Long', 'Đảo hoang sơ với bãi biển đẹp', 20.9833, 107.9333, 'island', 'https://images.unsplash.com/bach-long.jpg', 580, false, NOW()),
(uuid_generate_v4(), 'Trường Sa', 'Quần đảo Trường Sa huyền bí', 8.6500, 111.9167, 'island', 'https://images.unsplash.com/truong-sa.jpg', 640, false, NOW()),
(uuid_generate_v4(), 'Thổ Chu', 'Quần đảo với rạn san hô tuyệt đẹp', 9.3167, 103.4833, 'island', 'https://images.unsplash.com/tho-chu.jpg', 580, false, NOW()),
(uuid_generate_v4(), 'Hòn Sơn', 'Đảo ngọc với bãi biển hoang sơ', 9.8333, 104.5833, 'island', 'https://images.unsplash.com/hon-son.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Cù Lao Câu', 'Đảo hoang sơ với san hô và cá đầy', 8.7333, 106.6000, 'island', 'https://images.unsplash.com/cu-lao-cau.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Hương Tích Cave', 'Động Hương Tích với hang động đẹp', 18.3333, 105.4167, 'cave', 'https://images.unsplash.com/huong-tich.jpg', 640, false, NOW()),
(uuid_generate_v4(), 'Pù Mạo National Park', 'Vườn quốc gia Pù Mạo với khỉ', 20.1500, 104.9167, 'forest', 'https://images.unsplash.com/xuan-vien.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Pù Hoạt National Park', 'Vườn quốc gia Pù Hoạt với rừng', 19.3500, 104.8667, 'forest', 'https://images.unsplash.com/pu-hoat.jpg', 600, false, NOW()),
(uuid_generate_v4(), 'Vạn Phần Mangrove', 'Rừng ngập mặn Vạn Phần', 14.3500, 109.0167, 'forest', 'https://images.unsplash.com/binh-dinh.jpg', 480, false, NOW()),
(uuid_generate_v4(), 'Côn Đảo Beach', 'Bãi biển hoang sơ Côn Đảo', 8.7333, 106.6333, 'island', 'https://images.unsplash.com/con-dao-2.jpg', 820, true, NOW()),
(uuid_generate_v4(), 'Bãi Dài', 'Bãi biển dài và đẹp ở Phú Quốc', 10.2167, 103.9833, 'island', 'https://images.unsplash.com/bai-dai.jpg', 780, false, NOW()),
(uuid_generate_v4(), 'Hòn Rong', 'Đảo hoang sơ với san hô', 10.5167, 104.0333, 'island', 'https://images.unsplash.com/hon-rong.jpg', 540, false, NOW()),
(uuid_generate_v4(), 'Thiên Viên Hòn Bồng', 'Thiên viên rừng nhiệt đới', 12.0500, 108.7000, 'forest', 'https://images.unsplash.com/hon-bong.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Mang Yang Pass', 'Đèo Mã Yáng với cảnh quan núi', 13.7500, 108.6833, 'mountain', 'https://images.unsplash.com/mang-yang.jpg', 580, false, NOW()),
(uuid_generate_v4(), 'Chà Là Island', 'Đảo Chà Là với rạn san hô', 10.7500, 108.2500, 'island', 'https://images.unsplash.com/cha-la.jpg', 520, false, NOW()),
(uuid_generate_v4(), 'Bình Hưng Island', 'Đảo Bình Hưng với bãi biển xanh', 9.2333, 104.5833, 'island', 'https://images.unsplash.com/binh-hung.jpg', 680, false, NOW()),
(uuid_generate_v4(), 'Hòn Hải', 'Đảo Hòn Hải với hang động', 12.6167, 109.4167, 'island', 'https://images.unsplash.com/hon-hai.jpg', 560, false, NOW()),
(uuid_generate_v4(), 'Đảo Bình Ba', 'Đảo san hô với bãi biển đẹp', 11.8167, 109.0167, 'island', 'https://images.unsplash.com/binh-ba.jpg', 720, false, NOW()),
(uuid_generate_v4(), 'Hòn Đỏ Island', 'Đảo với bãi cát đỏ độc đáo', 12.6833, 109.3500, 'island', 'https://images.unsplash.com/hon-do.jpg', 540, false, NOW()),
(uuid_generate_v4(), 'Tam Hải Island', 'Đảo Tam Hải với bãi biển yên tĩnh', 15.1167, 108.7333, 'island', 'https://images.unsplash.com/tam-hai.jpg', 620, false, NOW()),
(uuid_generate_v4(), 'Bàng Mountain', 'Núi Bàng với rừng và thác', 15.1833, 108.7833, 'mountain', 'https://images.unsplash.com/bang-mountain.jpg', 580, false, NOW()),
(uuid_generate_v4(), 'Phước Hải Beach', 'Bãi biển hoang sơ Phước Hải', 10.6833, 107.1333, 'coast', 'https://images.unsplash.com/phuoc-hai.jpg', 640, false, NOW()),
(uuid_generate_v4(), 'Long Hải Beach', 'Bãi biển Long Hải với bình minh', 10.3833, 107.2500, 'coast', 'https://images.unsplash.com/long-hai.jpg', 600, false, NOW()),
(uuid_generate_v4(), 'Non Nước Beach', 'Bãi biển Non Nước - Cảnh đẹp Việt Nam', 15.9333, 108.4500, 'coast', 'https://images.unsplash.com/non-nuoc.jpg', 780, true, NOW()),
(uuid_generate_v4(), 'Sa Pa Town', 'Thị trấn Sapa với ruộng bậc thang', 22.3400, 103.8440, 'mountain', 'https://images.unsplash.com/sapa-town.jpg', 860, true, NOW()),
(uuid_generate_v4(), 'Mường Hoa Valley', 'Thung lũng Mường Hoa với ruộng', 22.3667, 103.8167, 'mountain', 'https://images.unsplash.com/muong-hoa.jpg', 740, false, NOW()),
(uuid_generate_v4(), 'O Quy Ho Pass', 'Đèo Ô Quy Hồ - một trong tứ đại đỉnh đèo', 22.2833, 103.9500, 'mountain', 'https://images.unsplash.com/o-quy-ho.jpg', 820, true, NOW()),
(uuid_generate_v4(), 'Thác Bản Giốc', 'Thác nước lớn nhất Việt Nam', 22.8667, 106.7167, 'waterfall', 'https://images.unsplash.com/ban-gioc.jpg', 850, true, NOW()),
(uuid_generate_v4(), 'Động Puong', 'Hang động Puong với dòng sông ngầm', 22.6833, 106.1833, 'cave', 'https://images.unsplash.com/puong-cave.jpg', 720, false, NOW()),
(uuid_generate_v4(), 'Hồ Ba Bể', 'Hồ nước ngọt lớn nhất Việt Nam', 22.4417, 105.6167, 'lake', 'https://images.unsplash.com/ho-ba-be.jpg', 780, true, NOW()),
(uuid_generate_v4(), 'Đèo Mã Pì Lèng', 'Đèo Mã Pì Lèng - vua của các đỉnh đèo', 23.0833, 105.3500, 'mountain', 'https://images.unsplash.com/ma-pi-leng.jpg', 880, true, NOW()),
(uuid_generate_v4(), 'Mậu Duệ Valley', 'Thung lủng Mậu Duệ hoang sơ', 23.1500, 105.2833, 'mountain', 'https://images.unsplash.com/mau-duệ.jpg', 760, false, NOW()),
(uuid_generate_v4(), 'Núi Đọi', 'Núi Đọi với đền thờ và cảnh quan', 20.1833, 105.8833, 'mountain', 'https://images.unsplash.com/nui-doi.jpg', 580, false, NOW());

-- ============================================
-- MOCK: tracklog_categories (hierarchical)
-- ============================================
INSERT INTO public.tracklog_categories (id, name, description, icon, color, parent_id) VALUES
(uuid_generate_v4(), 'Mountain', 'Cao nguyên miền núi', '🏔️', '#FF6B35', NULL),
(uuid_generate_v4(), 'Forest', 'Rừng nguyên sinh', '🌲', '#228B22', NULL),
(uuid_generate_v4(), 'Beach', 'Bờ biển và đảo', '🏖️', '#00CED1', NULL),
(uuid_generate_v4(), 'Cave', 'Hang động', '🕳️', '#8B4513', NULL),
(uuid_generate_v4(), 'Waterfall', 'Thác nước', '💧', '#4169E1', NULL),
(uuid_generate_v4(), 'Heritage', 'Di sản thế giới', '🏛️', '#FFD700', NULL),
(uuid_generate_v4(), 'Island', 'Đảo và quần đảo', '🏝️', '#FF69B4', NULL),
(uuid_generate_v4(), 'Lake', 'Hồ và đầm nước', '🏞️', '#20B2AA', NULL),
(uuid_generate_v4(), 'River', 'Sông và kênh rạch', '🚣', '#4682B4', NULL),
(uuid_generate_v4(), 'Highland', 'Cao nguyên và vùng cao', '⛰️', '#9ACD32', NULL),
(uuid_generate_v4(), 'City', 'Thành phố và đô thị', '🏙️', '#808080', NULL),
(uuid_generate_v4(), 'Coast', 'Vùng ven biển', '🌊', '#F0E68C', NULL);

-- ============================================
-- MOCK: tracklog_tags (50 tags)
-- ============================================
INSERT INTO public.tracklog_tags (id, name) VALUES
(uuid_generate_v4(), 'sunrise'),
(uuid_generate_v4(), 'sunset'),
(uuid_generate_v4(), 'camping'),
(uuid_generate_v4(), 'swimming'),
(uuid_generate_v4(), 'photography'),
(uuid_generate_v4(), 'family-friendly'),
(uuid_generate_v4(), 'overnight'),
(uuid_generate_v4(), 'scenic'),
(uuid_generate_v4(), 'wildlife'),
(uuid_generate_v4(), 'cultural'),
(uuid_generate_v4(), 'adventure'),
(uuid_generate_v4(), 'relaxation'),
(uuid_generate_v4(), 'nature'),
(uuid_generate_v4(), 'waterfalls'),
(uuid_generate_v4(), 'flowers'),
(uuid_generate_v4(), 'rice-terrace'),
(uuid_generate_v4(), 'summit'),
(uuid_generate_v4(), 'jungle'),
(uuid_generate_v4(), 'coastal'),
(uuid_generate_v4(), 'island-hopping'),
(uuid_generate_v4(), 'cave-exploration'),
(uuid_generate_v4(), 'river-trek'),
(uuid_generate_v4(), 'homestay'),
(uuid_generate_v4(), 'local-food'),
(uuid_generate_v4(), 'off-the-beaten-path'),
(uuid_generate_v4(), 'popular'),
(uuid_generate_v4(), 'hidden-gem'),
(uuid_generate_v4(), 'stargazing'),
(uuid_generate_v4(), 'bird-watching'),
(uuid_generate_v4(), 'trekking'),
(uuid_generate_v4(), 'climbing'),
(uuid_generate_v4(), 'kayaking'),
(uuid_generate_v4(), 'cycling'),
(uuid_generate_v4(), 'motorbike'),
(uuid_generate_v4(), 'multi-day'),
(uuid_generate_v4(), 'single-day'),
(uuid_generate_v4(), 'misty'),
(uuid_generate_v4(), 'cloud-hunting'),
(uuid_generate_v4(), 'foggy'),
(uuid_generate_v4(), 'dry-season'),
(uuid_generate_v4(), 'rainy-season'),
(uuid_generate_v4(), 'winter'),
(uuid_generate_v4(), 'spring'),
(uuid_generate_v4(), 'summer'),
(uuid_generate_v4(), 'autumn'),
(uuid_generate_v4(), 'festival'),
(uuid_generate_v4(), 'pilgrimage'),
(uuid_generate_v4(), 'historical'),
(uuid_generate_v4(), 'eco-tourism'),
(uuid_generate_v4(), 'wilderness'),
(uuid_generate_v4(), 'navigation'),
(uuid_generate_v4(), 'first-aid'),
(uuid_generate_v4(), 'safety'),
(uuid_generate_v4(), 'backpacking'),
(uuid_generate_v4(), 'car-camping'),
(uuid_generate_v4(), 'glamping'),
(uuid_generate_v4(), 'budget'),
(uuid_generate_v4(), 'luxury'),
(uuid_generate_v4(), 'family'),
(uuid_generate_v4(), 'couple'),
(uuid_generate_v4(), 'solo'),
(uuid_generate_v4(), 'group'),
(uuid_generate_v4(), 'pet-friendly'),
(uuid_generate_v4(), 'kids-friendly'),
(uuid_generate_v4(), 'senior-friendly'),
(uuid_generate_v4(), 'beginner'),
(uuid_generate_v4(), 'intermediate'),
(uuid_generate_v4(), 'expert'),
(uuid_generate_v4(), 'sunrise-trek'),
(uuid_generate_v4(), 'sunset-trek'),
(uuid_generate_v4(), 'night-trek'),
(uuid_generate_v4(), 'full-moon'),
(uuid_generate_v4(), 'new-moon'),
(uuid_generate_v4(), 'weekend-trip'),
(uuid_generate_v4(), 'holiday'),
(uuid_generate_v4(), 'Leave No Trace'),
(uuid_generate_v4(), 'sustainable'),
(uuid_generate_v4(), 'responsible-travel'),
(uuid_generate_v4(), 'local-guide'),
(uuid_generate_v4(), 'trail-running'),
(uuid_generate_v4(), 'orientation'),
(uuid_generate_v4(), 'gps-navigation'),
(uuid_generate_v4(), 'off-route-alert'),
(uuid_generate_v4(), 'offline-map'),
(uuid_generate_v4(), 'easy-access'),
(uuid_generate_v4(), 'remote'),
(uuid_generate_v4(), 'crowded'),
(uuid_generate_v4(), 'peaceful'),
(uuid_generate_v4(), 'challenging'),
(uuid_generate_v4(), 'rewarding-views'),
(uuid_generate_v4(), 'cultural-immersion'),
(uuid_generate_v4(), 'photography-spots'),
(uuid_generate_v4(), 'sunrise-viewpoint'),
(uuid_generate_v4(), 'sunset-viewpoint'),
(uuid_generate_v4(), 'sunrise-spot'),
(uuid_generate_v4(), 'sunset-spot'),
(uuid_generate_v4(), 'panoramic-views'),
(uuid_generate_v4(), 'breathtaking');

-- ============================================
--